### ISSUE TITLE
May I ask which dataset do you use to train the network?

### ISSUE THREAD

**Issue by tkamkb** [joeyism/py-image-comparer#1]
I use Omniglots dataset to train my Siamese Net, but the network doesn't test well in the real world images. I find your comparer works well in the real world images, May I ask which dataset do you use to train Siamese Net?

**Comment by joeyism** [comment]
I used Omniglots too, and I got a precision of 0.9175 by the end. What precision did you get?

**Comment by tkamkb** [comment]
89% or so, my model doesn't work well on rgb light-change images.

**Comment by joeyism** [comment]
Hmmm without analyzing deeper, I can't really speak on the differences

**Comment by tkamkb** [comment]
Thanks
